### ISSUE TITLE
Extend intermediate Data Model (BpmnObject)

### ISSUE THREAD

**Issue by ahsNT** [NovatecConsulting/camunda-bpmn-documentation-generator#16]

**Comment by ykstr** [comment]
Weitere Felder: 
* Prozesszweck/Goal/Purpose/Documentation (Path: bpmn:process.bpmn:documentation)
* Element Documentation (Path: z.B. bpmn:process.bpmn:startEvent.bpmn:documentation)

**Comment by ykstr** [comment]
Multiple classes:
* Lane
* Process
* Element
* Object (Abstrakte Oberklasse, hält Name, ID, Documentation)
* StartEventEnum
