### ISSUE TITLE
FileAlreadyExistsException when more than one bpmn-files exist in source directory

### ISSUE THREAD

**Issue by jenshb** [NovatecConsulting/camunda-bpmn-documentation-generator#47]
When more than one *.bpmn-File exists in the source directory (main/resources/bpmn), the maven plugin throws
java.nio.file.FileAlreadyExistsException: /Users/jbr/git/ahsNT/cbdg-maven-test/target/cbdg/html/images/flowchart.png

**Reason**
The file configured as bpmnDiagramImageFile is copied to the target directory for every processed bpmn-File

**Suggested solution**
It should be possible to configure a separate image for each file

**Comment by kwiens12357** [comment]
https://github.com/NovatecConsulting/cbdg-maven-test/pull/8
https://github.com/NovatecConsulting/camunda-bpmn-documentation-generator/pull/48
